### ISSUE TITLE
Não funciona no Windows

### ISSUE THREAD

**Issue by danilosousa** [cobasilabs/generate-nodejs-app#1]
Tentei fazer a instalação no windows e não funcionou na hora de selecionar NPM ou YARN

**Comment by rodrigoyoshida** [comment]
Realmente, em um determinado momento redirecionamos as mensagems pro /dev/null pra não poluir o terminal, no Windows não existe o /dev/null.

**Comment by rodrigoyoshida** [comment]
Boa! PR aceito.
